import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import {
  Typography
} from '@material-ui/core';
import {
  yellow
} from '@material-ui/core/colors';
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Image
        className={styles.heroBackground}
        src="/images/title-page.png"
        alt="Next.js Logo"
        fill
        style={{objectFit:'cover', objectPosition: 'center'}}
      />
        <div className={styles.homeMenu}>
          <div>
            <Typography
              variant="h1"
              style={{color: yellow[600], fontWeight: 'bold', fontFamily: 'Henny Penny'}}>
                House Cup Trivia
            </Typography>
            <Link style={{textDecoration: 'none'}} href='/trivia/'>
              <Typography
                variant='h2'
                style={{color: 'white', fontWeight: 'bold', fontFamily: 'Henny Penny', margin: 32}}
                >Book 2: The Chamber of Secrets</Typography>
            </Link>
            <Link style={{textDecoration: 'none'}} href='/book2/trivia/'>
              <Typography
                variant='h2'
                style={{color: 'white', fontWeight: 'bold', fontFamily: 'Henny Penny', margin: 32}}
                >Book 3: The Prisoner of Azkaban</Typography>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
